url: http://rosshomes.co.nz

# Site settings
title: Ross Homes
email:
description: "Ross Homes Limited"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c09f80
  secondary: c09f80
  secondary-dark: 333

#
# Postal address (add as many lines as necessary)
address:
  - line: 6 Pounamu Avenue
  - line: Greenhithe, Auckland, 0632

# Build settings
markdown: kramdown
permalink: pretty
